In [1]:
import pandas as pd
import numpy as np

# Changing Options with Attributes and Dot Syntax

In [4]:
data = np.random.randint(0, 100, [1000, 50])
df = pd.DataFrame(data)
df.tail(2)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
998,26,41,27,12,97,81,1,62,69,74,...,94,3,28,49,71,14,87,95,39,3
999,22,67,54,41,17,8,26,91,24,97,...,63,49,55,90,95,51,52,95,17,48

In [8]:
pd.options.display.max_rows = 4

In [13]:
pd.options.display.max_columns = 8

In [14]:
df

     0   1   2   3  ...  46  47  48  49
0    69  70   6   0 ...  77  72  97   9
1    94  83  73  17 ...  26   5  71  26
..   ..  ..  ..  .. ...  ..  ..  ..  ..
998  26  41  27  12 ...  87  95  39   3
999  22  67  54  41 ...  52  95  17  48

[1000 rows x 50 columns]

# Changing pandas Options with Methods

In [15]:
data = np.random.randint(0, 100, [1000, 50])
df = pd.DataFrame(data)
df.tail(2)

     0   1   2   3  ...  46  47  48  49
998   0   9  80   9 ...  75  20  59  94
999  61  70  32   4 ...  64  76   2  47

[2 rows x 50 columns]

In [16]:
pd.get_option('max_rows')

4

In [17]:
pd.get_option('max_columns')

8

In [18]:
pd.set_option('max_rows', 16)

In [19]:
df

     0   1   2   3  ...  46  47  48  49
0    28  89  16  65 ...  41  44  30  57
1    86  31  54  42 ...  41  22  93  46
2    13  68  35  88 ...  58  61  27  16
3    23  32  35  87 ...  78  92   2  26
4    77  73  72  27 ...   1  35  50   6
5    99  36  20  40 ...  75  24  95  85
6    20  46   7  41 ...  72  97  70  24
7     8  78  85  59 ...  53  60  82  43
..   ..  ..  ..  .. ...  ..  ..  ..  ..
992  39  32  65  45 ...  20  72  74  93
993  10  66  53  64 ...  25  41  97  38
994  59  33  80  83 ...  12  71  74  93
995  19  78  43   0 ...  64  71  13  26
996  93  44  33   5 ...  30  84  69  21
997  88  74  89  37 ...  41   0  86  19
998   0   9  80   9 ...  75  20  59  94
999  61  70  32   4 ...  64  76   2  47

[1000 rows x 50 columns]

In [20]:
pd.set_option('max_columns', 20)

In [21]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,28,89,16,65,83,50,36,2,42,11,...,58,32,92,40,2,17,41,44,30,57
1,86,31,54,42,82,80,38,76,17,41,...,94,58,24,97,51,69,41,22,93,46
2,13,68,35,88,0,49,78,66,61,48,...,86,67,99,86,34,53,58,61,27,16
3,23,32,35,87,70,41,86,76,49,2,...,3,62,43,24,45,75,78,92,2,26
4,77,73,72,27,32,48,84,13,30,61,...,73,66,35,42,38,81,1,35,50,6
5,99,36,20,40,84,82,64,40,40,28,...,5,62,61,33,24,4,75,24,95,85
6,20,46,7,41,8,60,83,95,67,59,...,32,94,66,32,34,1,72,97,70,24
7,8,78,85,59,23,65,89,40,69,30,...,98,32,1,6,47,14,53,60,82,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,39,32,65,45,87,21,25,19,85,56,...,28,78,25,2,44,22,20,72,74,93
993,10,66,53,64,65,7,6,72,37,13,...,53,0,60,98,73,62,25,41,97,38
994,59,33,80,83,93,29,43,66,55,8,...,8,35,98,98,94,17,12,71,74,93
995,19,78,43,0,82,81,76,95,41,35,...,36,65,49,22,90,80,64,71,13,26
996,93,44,33,5,87,70,15,69,73,39,...,5,9,55,74,50,2,30,84,69,21
997,88,74,89,37,80,1,0,34,94,80,...,70,5,14,67,38,78,41,0,86,19
998,0,9,80,9,32,27,25,95,49,5,...,91,31,67,81,70,1,75,20,59,94
999,61,70,32,4,15,88,88,78,65,81,...,8,15,44,54,50,23,64,76,2,47

In [22]:
pd.reset_option('max_columns')
pd.reset_option('max_rows')

In [23]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,28,89,16,65,83,50,36,2,42,11,...,58,32,92,40,2,17,41,44,30,57
1,86,31,54,42,82,80,38,76,17,41,...,94,58,24,97,51,69,41,22,93,46
2,13,68,35,88,0,49,78,66,61,48,...,86,67,99,86,34,53,58,61,27,16
3,23,32,35,87,70,41,86,76,49,2,...,3,62,43,24,45,75,78,92,2,26
4,77,73,72,27,32,48,84,13,30,61,...,73,66,35,42,38,81,1,35,50,6
5,99,36,20,40,84,82,64,40,40,28,...,5,62,61,33,24,4,75,24,95,85
6,20,46,7,41,8,60,83,95,67,59,...,32,94,66,32,34,1,72,97,70,24
7,8,78,85,59,23,65,89,40,69,30,...,98,32,1,6,47,14,53,60,82,43
8,21,53,88,73,92,92,74,53,83,45,...,87,33,7,10,3,59,37,18,51,19
9,5,13,82,39,2,69,21,31,15,45,...,9,63,80,84,93,77,44,0,54,57
10,27,88,59,18,88,81,39,97,44,2,...,15,25,80,7,20,71,74,95,14,49
11,83,77,38,98,34,10,58,58,8,73,...,95,58,98,2,33,85,76,22,28,44
12,46,33,79,66,67,1,16,33,70,44,...,68,56,80,79,60,88,33,21,19,40
13,85,18,23,1,8,70,0,38,93,49,...,23,88,31,48,49,42,65,20,42,48
14,15,31,91,26,30,22,73,44,2,90,...,24,61,54,91,96,94,20,85,48,63
15,75,90,32,31,39,80,11,70,30,49,...,88,70,71,83,97,35,66,37,53,36
16,72,98,96,2,4,4,86,58,20,93,...,26,48,42,69,14,37,24,44,60,66
17,32,98,40,91,2,91,37,20,59,60,...,90,55,32,30,11,24,81,41,40,85
18,82,30,82,76,80,17,64,62,80,13,...,90,46,65,3,95,20,45,12,75,78
19,32,43,79,86,96,71,50,56,72,75,...,37,26,55,53,80,45,12,71,96,26
20,89,1,73,80,41,14,74,75,20,5,...,52,98,88,61,52,61,65,62,32,7
21,35,43,16,1,92,20,33,32,29,73,...,29,39,75,92,83,30,34,19,81,51
22,45,63,25,76,81,59,70,28,97,10,...,0,54,46,25,7,88,13,13,43,32
23,22,70,68,53,98,3,94,31,9,16,...,89,87,18,68,4,31,2,11,50,54
24,81,43,75,32,66,73,89,82,6,39,...,18,43,99,49,60,52,23,39,39,10
25,35,55,46,34,5,34,81,29,65,25,...,48,46,58,24,92,49,40,47,8,40
26,94,3,50,96,99,28,44,28,45,3,...,11,42,11,57,2,13,63,7,18,72
27,79,52,26,84,86,45,34,63,83,48,...,85,72,3,13,22,92,82,29,35,7
28,5,51,54,91,51,95,66,68,92,22,...,67,2,39,94,69,21,58,23,17,90
29,39,4,26,84,50,85,36,48,72,15,...,55,38,85,48,13,92,91,39,17,63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,42,59,42,30,92,35,77,21,23,22,...,77,2,33,42,32,10,28,24,53,45
971,57,16,98,31,65,45,24,24,97,36,...,78,77,60,98,71,54,85,67,64,33
972,60,12,30,65,85,64,61,89,26,45,...,87,71,3,32,68,98,25,65,56,80
973,54,45,36,7,61,7,62,1,55,73,...,68,0,92,73,20,69,66,96,88,39
974,39,19,54,52,92,62,14,72,21,87,...,3,48,31,34,37,40,47,39,67,54
975,74,36,0,27,77,76,43,92,64,90,...,32,47,8,46,26,17,46,97,13,92
976,24,73,54,77,0,63,46,90,84,40,...,0,32,19,59,8,45,96,43,63,47
977,52,20,4,72,78,35,87,37,11,63,...,63,28,63,59,15,78,17,90,99,47
978,79,55,22,28,12,85,38,71,93,93,...,63,57,24,68,68,84,30,57,35,79
979,41,45,84,20,43,39,69,32,42,91,...,26,0,91,48,18,17,73,82,77,98
980,47,20,38,2,74,75,6,84,72,53,...,92,63,76,47,65,8,9,92,32,15
981,65,58,93,95,3,49,20,94,80,24,...,38,38,90,68,53,54,88,59,95,45
982,65,23,18,50,87,91,44,2,98,99,...,89,39,95,44,44,50,18,98,27,46
983,92,80,6,13,9,70,37,31,64,64,...,54,19,11,26,56,26,16,44,44,50
984,86,64,76,8,43,4,63,61,67,54,...,37,55,90,35,26,3,8,83,63,83
985,49,37,67,62,54,90,65,49,21,78,...,97,67,56,21,39,77,39,62,98,25
986,8,74,62,12,29,84,18,29,99,21,...,40,95,34,52,25,80,0,18,10,67
987,77,44,44,16,83,25,99,83,59,37,...,78,76,23,60,30,21,21,63,21,42
988,60,37,69,80,80,43,56,82,88,24,...,20,35,76,37,64,59,88,63,15,99
989,55,33,91,3,70,6,41,4,76,9,...,56,99,54,62,34,86,54,55,93,45
990,60,20,88,13,50,93,56,4,27,93,...,92,30,98,78,74,46,88,25,40,88
991,41,86,37,44,53,27,22,14,22,33,...,25,17,49,89,33,75,13,91,40,40
992,39,32,65,45,87,21,25,19,85,56,...,28,78,25,2,44,22,20,72,74,93
993,10,66,53,64,65,7,6,72,37,13,...,53,0,60,98,73,62,25,41,97,38
994,59,33,80,83,93,29,43,66,55,8,...,8,35,98,98,94,17,12,71,74,93
995,19,78,43,0,82,81,76,95,41,35,...,36,65,49,22,90,80,64,71,13,26
996,93,44,33,5,87,70,15,69,73,39,...,5,9,55,74,50,2,30,84,69,21
997,88,74,89,37,80,1,0,34,94,80,...,70,5,14,67,38,78,41,0,86,19
998,0,9,80,9,32,27,25,95,49,5,...,91,31,67,81,70,1,75,20,59,94
999,61,70,32,4,15,88,88,78,65,81,...,8,15,44,54,50,23,64,76,2,47

In [24]:
pd.describe_option('max_columns')

display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 20] [currently: 20]

# The precision Option

In [26]:
df = pd.DataFrame(np.random.randn(5, 5))
df

          0         1         2         3         4
0  1.939616 -0.884907 -0.034482  0.356444 -1.054127
1 -2.197603  0.887932  1.074491 -0.813521  0.877711
2 -0.911482  0.114324 -0.975062 -0.809335  0.380277
3 -0.032199  0.413054 -0.435544  0.297820 -0.941221
4  1.913745 -0.161958 -0.725830 -0.956030  0.391041

In [27]:
pd.get_option('precision')

6

In [28]:
pd.set_option('precision', 2)

In [29]:
df

      0     1     2     3     4
0  1.94 -0.88 -0.03  0.36 -1.05
1 -2.20  0.89  1.07 -0.81  0.88
2 -0.91  0.11 -0.98 -0.81  0.38
3 -0.03  0.41 -0.44  0.30 -0.94
4  1.91 -0.16 -0.73 -0.96  0.39

In [30]:
pd.reset_option('precision')

In [31]:
df

          0         1         2         3         4
0  1.939616 -0.884907 -0.034482  0.356444 -1.054127
1 -2.197603  0.887932  1.074491 -0.813521  0.877711
2 -0.911482  0.114324 -0.975062 -0.809335  0.380277
3 -0.032199  0.413054 -0.435544  0.297820 -0.941221
4  1.913745 -0.161958 -0.725830 -0.956030  0.391041